name: Snap workflow
on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: boolean

jobs:
  build-snap:
    runs-on: ubuntu-latest
    outputs:
      snap_name: ${{ steps.snapcraft.outputs.snap }}
      channel: ${{ steps.channel.outputs.channel }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: channel
      run: |
        if git describe --exact-match; then
          echo "::set-output name=channel::candidate"
        else
          echo "::set-output name=channel::edge"
        fi
    - id: prep
      run: |
        mkdir -p snap
        ln -s ../contrib/snap/snapcraft.yaml snap/snapcraft.yaml
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}

